// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $contact from "./routes/contact.ts";
import * as $index from "./routes/index.tsx";
import * as $Contact from "./islands/Contact.tsx";
import * as $Hero from "./islands/Hero.tsx";
import * as $QuoteButton from "./islands/QuoteButton.ts";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/contact.ts": $contact,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Contact.tsx": $Contact,
    "./islands/Hero.tsx": $Hero,
    "./islands/QuoteButton.ts": $QuoteButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
